# Run Configuration for tower_treasures Game

# Target modes for optimization
target_modes = ["base", "bonus"]

[execution]
num_threads = 10
rust_threads = 20
batching_size = 50000
compression = false
profiling = false

[simulation]
base = 1000
bonus = 1000

[pipeline]
run_sims = true
run_optimization = false
run_analysis = false
run_format_checks = true

[analysis]
custom_keys = [{ symbol = "scatter" }]
